name: pty
description: Pty for Dart and Flutter. Provides the ability to create processes with pseudo terminal file descriptors.
version: 0.2.0-pre
homepage: https://github.com/TerminalStudio/pty

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  win32: ^2.0.2
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
